BATCH_SIZE = 17
IMG_SIZE = 224
NUM_CLASSES = 35
NUM_EPOCHS = 10
NUM_HEADS = 4

LEARNING_RATE = 1e-04
MIN_LR = 1e-6
LR_SCHEDULER_GAMMA = 0.8
WEIGHT_DECAY = 1e-04

USE_LR_SCHEDULER = True
APPLY_GRADIENT_CLIPPING = True

DROPOUT_CLASSIFICATION = 0.2
NUM_CLUSTERS = 10