BATCH_SIZE = 32
IMG_SIZE = 32
NUM_CLASSES = 10
NUM_EPOCHS = 20
NUM_HEADS = 4
INITIAL_EMBED_DIM = 96

LEARNING_RATE = 1e-04
MIN_LR = 1e-6
LR_SCHEDULER_GAMMA = 0.8
WEIGHT_DECAY = 1e-04

USE_LR_SCHEDULER = True
APPLY_GRADIENT_CLIPPING = True

DROPOUT_CLASSIFICATION = 0.2
NUM_CLUSTERS = 25

USE_RANDOM_DATASET = False
NUM_RANDOM_SAMPLES = 1000

TRAIN_BASE_PATH = './tiny-imagenet-200/tiny-imagenet-200/train'
VALID_BASE_PATH = 'tiny-imagenet-200/tiny-imagenet-200/val/images'
VALID_ANNOTATIONS_PATH = 'tiny-imagenet-200/tiny-imagenet-200/val/val_annotations.txt'

MODEL_SAVE_BASE_PATH = './saved_models'

SEED = 42

IMAGENET2000LOCAL = 'imagenet200local'
CIFAR10HUGGINGFACE = 'cifar10huggingface'
DATASET = CIFAR10HUGGINGFACE